# Generated by Django 5.2.3 on 2025-06-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fillapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="UserGroup",
        ),
    ]
